package main

import (
	"OmeSatoFoundation/itschool_dist_gen/copy_llmk_object/copy_obj"
	"OmeSatoFoundation/itschool_dist_gen/copy_llmk_object/extract"
	"OmeSatoFoundation/itschool_dist_gen/copy_llmk_object/generated_files"
	"fmt"
	"log"
	"os"
)

type ParseCommandLineArgumentError struct{}

func (*ParseCommandLineArgumentError) Error() string {
	return fmt.Sprintf(`
Usage:

%s <destination>

Copy intermediate/object files generated by latex.


This program first gets source file names from llmk.toml in the cwd and
copy below list files to <destination> where %%B is the base name of the
source file names:

%%B.aux, %%B.bbl, %%B.bcf, %%B-blx.bib, %%B.blg, %%B.fls, %%B.idx, %%B.ilg,
%%B.ind, %%B.lof, %%B.log, %%B.lot, %%B.nav, %%B.out, %%B.run.xml, %%B.snm,
%%B.toc, %%B.vrb %%B.pdf

This list inherits https://github.com/wtsnjp/llmk/blob/e9949790d4acd007b58aa80d60aa2b4c18953134/llmk.lua#L58
`, os.Args[0])
}

func parseClargs() (string, error) {
	if len(os.Args) != 2 {
		return "", &ParseCommandLineArgumentError{}
	}
	return os.Args[1], nil
}

func main() {
	destDir, err := parseClargs()
	if err != nil {
		log.Fatal(err)
	}
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	sources, err := extract.ExtractSourcesInLLMKToml(cwd)
	if err != nil {
		log.Fatal(err)
	}
	generated_files := generated_files.ListGeneratedFiles(sources)
	err = copy_obj.Copy(generated_files, destDir)
	if err != nil {
		log.Fatal(err)
	}
}
