Document: ome2023
Title: Debian ome2023 Manual
Author: <insert document author here>
Abstract: This manual describes what ome2023 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ome2023/ome2023.sgml.gz

Format: postscript
Files: /usr/share/doc/ome2023/ome2023.ps.gz

Format: text
Files: /usr/share/doc/ome2023/ome2023.text.gz

Format: HTML
Index: /usr/share/doc/ome2023/html/index.html
Files: /usr/share/doc/ome2023/html/*.html
