name: Build and Push ome-doc Container Image

on:
  push:
    tags:
      - "*"
      - "buildenv-**"
    branches:
      - "workflow-dev"

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    env:
      IMAGE_NAME: texlive
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "false"
    - name: Rewrite GitHub SSH URLs to HTTPS for CI
      run: |
        git config --global --add url."https://github.com/".insteadOf "git@github.com:"
        git config --global --add url."https://github.com/".insteadOf "ssh://git@github.com/"
    - name: Initialize submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create the GitHub Repository Name with All Small Cases
      run: |
        echo "REPOSITORY_NAME_LC=${REPOSITORY_NAME,,}" >>"${GITHUB_ENV}"
      env:
        REPOSITORY_NAME: '${{ github.repository }}'
    # TODO: Use loops instead of listing up all the chapters.
    - name: Build Chapter 01
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        target: "final"
        outputs: "type=local,dest=/artifact_01"
        file: "./docker/text.Dockerfile"
    - name: Upload Chapter 01
      uses: actions/upload_artifact@v6
      with:
        name: "itm01"
        path: "/artifact_01"

# Inherited by https://qiita.com/Jazuma/items/aca397e081a7825d0dec
